### ISSUE TITLE
Why not working?

### ISSUE THREAD

**Issue by lbg030** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#2]
I completely install requirements & submoules, then tried to run code.
But It is not working.
I think backend process is deadlocked, What should I do?\

![image](https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/assets/66514138/b98d154d-9d9a-4bb6-8e29-d9b9243545b1)

**Comment by Riboha** [comment]
The problem seems to have occurred because the system was started before the mapping process was fully prepared.
The tracking process reads the dataset, while mapping process is implemented to wait until the dataset is fully loaded. So this issue was unexpected and had not occurred in my environment before.
Thank you for raising this issue, and I have updated the code to address it. 
Please let me know if the same issue occurs again.

**Comment by hjr37** [comment]
Is the camera tracking performed in an already established or nearly established 3D Gaussian Field? I think that even the traditional ICP method struggles to achieve decent rendering quality while performing tracking at a speed of 100fps.

**Comment by hjr37** [comment]
Is the camera tracking performed in an already established or nearly established 3D Gaussian Field? I think that even the traditional ICP method struggles to achieve decent rendering quality while performing tracking at a speed of 100fps.

**Comment by ztmo520** [comment]
Thank you for your amazing work!

I experimented on two machines and on one of them, an RTX 3090, everything went fine, on the other, an RTX 3060, the same problem would occur.

I found that the code would get stuck at the location in Tracker, self.reg.align().

https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/blob/53fd4e60091ab2a099d817eba1abb349d6d3481a/mp_Tracker.py#L169

I did the python_tester test as instructed in the submodule /fast_gicp, and strangely, on both my computers, it gives me an error when running into the "align" position, segmentation fault (core dumped) or MemoryError: std::bad_alloc. This makes me very confused, because in gs_icp_slam.py it works fine on RTX 3090 machine.

I hope this info will give you some clues.

**Comment by mrkrustykreme** [comment]
Hi, I have just cloned the repo but am still experiencing the same error as @lbg030. Running on an RTX 4090.

> The problem seems to have occurred because the system was started before the mapping process was fully prepared. The tracking process reads the dataset, while mapping process is implemented to wait until the dataset is fully loaded. So this issue was unexpected and had not occurred in my environment before. Thank you for raising this issue, and I have updated the code to address it. Please let me know if the same issue occurs again.

**Comment by Riboha** [comment]
@ztmo520 Thank you for your efforts and for sharing your experience!!!
For GS-ICP SLAM, we use a modified version of our fast_gicp, which is on gs_icp_slam branch of it.
The python_tester is for the main branch of fast_gicp, and does not work with the gs_icp_slam version.

I'm testing GS-ICP SLAM in other environments, trying to reproduce this error. However, I haven't encountered this problem yet. Can you share some information about the environment of RTX 3060 desktop? (version of Ubuntu, cuda, torch ...) It will be helpful for me to tackle this problem!!

> Thank you for your amazing work!
> 
> I experimented on two machines and on one of them, an RTX 3090, everything went fine, on the other, an RTX 3060, the same problem would occur.
> 
> I found that the code would get stuck at the location in Tracker, self.reg.align().
> 
> https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/blob/53fd4e60091ab2a099d817eba1abb349d6d3481a/mp_Tracker.py#L169
> 
> I did the python_tester test as instructed in the submodule /fast_gicp, and strangely, on both my computers, it gives me an error when running into the "align" position, segmentation fault (core dumped) or MemoryError: std::bad_alloc. This makes me very confused, because in gs_icp_slam.py it works fine on RTX 3090 machine.
> 
> I hope this info will give you some clues.

**Comment by ztmo520** [comment]
@Riboha I experimented again on a new RTX 4090 machine and it is working fine. I found that it is fine on an ubuntu 20.04 machine, and will have problems on 22.04, I'm guessing it's an environment issue with compiling fast_gicp that is preventing it from working properly，like g++, pcl, vtk, etc.

**Comment by Riboha** [comment]
Thanks a lot @ztmo520!!!
I will test our system on ubuntu 22.04. If I can't find a solution to this problem, I'll provide a Docker image.

**Comment by while0l1** [comment]
For my ubuntu 20.04, downgrading pcl from version 1.12 to 1.10 solved the problem.

**Comment by Buffyqsf** [comment]
> Thanks a lot @ztmo520!!! I will test our system on ubuntu 22.04. If I can't find a solution to this problem, I'll provide a Docker image.

Hi have your tried on ubuntu22.04? I think I encountered the same problem.

**Comment by BetterYimi** [comment]
> For my ubuntu 20.04, downgrading pcl from version 1.12 to 1.10 solved the problem.

Hi, My pcl version also is 1.10 but fast_gicp still can not work,.Could you please tell me what  your openmp version and vtk version are？

**Comment by MarvinChung** [comment]
Thank you for your valuable contributions and the impressive work you've done.

I'm currently encountering same issues while using Ubuntu 22.04, and after some investigation, I suspect it's related to vtk.

This issue arises within the pcl_library in fast_gicp. The version of pcl_library being utilized is `pcl=1.12`, which corresponds to the default version installed on Ubuntu 22.04 via `sudo apt install libpcl-dev`.
```
fast_gicp
- pcl-1.12
    - vtk-v9.1.0
```
The root cause seems to stem from vtk-v9.1.0, as detailed in [this GitHub issue](https://github.com/PointCloudLibrary/pcl/issues/5237).

It's likely that this issue persists across Ubuntu versions 22.04, 22.10, and 23.04, as they all utilize vtk-v9.1.0 as the default version in their releases. [vtk: OS and version](https://docs.vtk.org/en/latest/getting_started/index.html#using-c-and-cmake)

A potential solution is to compile pcl with a specific version of vtk. I've personally tested compiling it with the following versions:
```
VTK-9.3.0
pcl-1.14.1
```
To begin, please follow the [instructions provided by vtk](https://docs.vtk.org/en/latest/build_instructions/index.html) to install the desired vtk version.

Then, remove the old pcl package:
```
sudo apt-get --purge remove libpcl-dev
```

Next, clone the pcl repository:
```
git clone https://github.com/PointCloudLibrary/pcl.git
cd pcl
git checkout pcl-1.14.1
mkdir build
cd build
cmake ..  -DCMAKE_BUILD_TYPE=Release -DVTK_DIR=(the path to the vtk build directory)
```

After executing the `cmake ..` command, please verify that VTK points to version `9.3.0` instead of `9.1.0`. Also, check if CMake reports any missing packages.
```
make
sudo make install
```

Once pcl is rebuilt with the new vtk version, proceed to rebuild fast_gicp:
```
cd GS_ICP_SLAM/submodules/fast_gicp/
mkdir build
cd build
cmake ..
make
cd ..
python setup.py install --user
```

This should resolve the problem for ubuntu 22.04

**Comment by huarzail** [comment]
> I completely install requirements & submoules, then tried to run code. But It is not working. I think backend process is deadlocked, What should I do?\
> 
> ![image](https://private-user-images.githubusercontent.com/66514138/316249523-b98d154d-9d9a-4bb6-8e29-d9b9243545b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjAxOTgsIm5iZiI6MTcyMTIxOTg5OCwicGF0aCI6Ii82NjUxNDEzOC8zMTYyNDk1MjMtYjk4ZDE1NGQtOWQ5YS00YmI2LThlMjktZDliOTI0MzU0NWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDEyMzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZGNmMzIxN2ExZjBmNjI5YjkzYjJhMDBjOWQyYzg3Zjc5ZTc0ZDBhOWY5MDA4MDJiZWRiMGVmNjljMTIxMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EURBj2VClHU90Bjtih-4Vs4CeM8fCzMP-Fm70Jdi_ys)

This error is same to me. I also attempt to use the gdb to tracking the error, but failed. Because it log nothing usefull info.
How to fix this unexpected error. Seeking the correct answers.
